config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
  resources :projects
  resources :project_roles
  resources :users
  resources :time_logs
  resources :form_bulk_time_logs
end

app/models/time_log.rb
class TimeLog < ApplicationRecord
    belongs_to :project
    belongs_to :user
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
    def index
        @time_logs = TimeLog.all
    end
    def new
    end
    def create
        @time_log = TimeLog.new(time_log_params)
        if( @time_log.save )
            redirect_to time_logs_path
        else
            redirect_to root_path
        end
    end

    def destroy 
        if TimeLog.find(params[:id]).destroy
            redirect_to time_logs_path
        else
            redirect_to root_path
        end
    end

    private

    def time_log_params
        params.require(:time_log).permit(
            :user_id, 
            :project_id,
            :week_num_id, 
            :date,
            :hours,
            :progress_comment
        )
    end
end

app/helpers/time_log_helper.rb
module TimeLogHelper
    def collect_weeks 
        select = []
        (-4..4).each do |i| #-4 to +4 weeks shown in drop down
            date_offset = Date.today + i.weeks

            select << [week_desc_from_date(date_offset), week_num_id(date_offset)]
        end
        select
    end

    def week_desc_from_date(date)
        format = "%b %d"
        date.beginning_of_week.strftime(format).to_s + " - " + date.end_of_week.strftime(format).to_s    
    end

    def week_desc_from_week_num_id(week_num_id)
        year = week_num_id.to_s[0,4]
        week_num = week_num_id.to_s[4,2]
        week_desc_from_date(Date.commercial(year.to_i, week_num.to_i))
    end

    def week_num_id(date)
        date.year.to_s + date.strftime("%W")
    end
end

app/views/time_logs/_index_nav.html.erb
<%=  link_to 'New', new_time_log_path %>

app/views/time_logs/index.html.erb
<%= render 'pages/level1_nav' %>
<h1>Time Logs</h1>
<%= render 'index_nav' %>


<table cellpadding="5">
    <tr>
        <th>delete?</th>
        <th>id</th>
        <th>week (week num id)</th>
        <th>date</th>
        <th>project</th>
        <th>user</th>
        <th>hours</th>
        <th>progress_comment</th>
    </tr>
    <% @time_logs.each do |time_log| %>
        <tr>
            <td><%= button_to "Delete", TimeLog.find(time_log.id), :method => :delete %></td>
            <td><%= time_log.id %></td>
            <td><%= week_desc_from_week_num_id(time_log.week_num_id) %> (<%= time_log.week_num_id%>)</td>
            <td><%= time_log.date %></td>
            <td><%= link_to time_log.project.name, project_path(time_log.project) %></td>
            <td><%= link_to time_log.user.last_name, user_path(time_log.user) %></td>
            <td><%= time_log.hours %></td>
            <td><%= time_log.progress_comment %></td>
        </tr>
    <%end %>
</table>

<br>

app/views/time_logs/new.html.erb
<%= render 'pages/level1_nav' %>
<h1>New Time Log</h1>

<%= form_with model: TimeLog do |form| %>
    <%= form.select :user_id, User.all.collect { |user| [user.last_name, user.id] }, {:prompt => "Select user"} %>
    <%= form.select :project_id, Project.all.collect { |project| [project.name, project.id] }, {:prompt => "Select project"}  %>
    <%= form.select :week_num_id, collect_weeks(), {:selected => week_num_id(Date.today)} %>
    <br>
    <br>
    <br>
    <br>
    <table>
        <tr>
            <th></th>
            <th><%= form.select :test1, Project.all.collect { |project| [project.name, project.id] }, {:prompt => "Select project"} %></th>
            <th><%= form.select :test2, Project.all.collect { |project| [project.name, project.id] }, {:prompt => "Select project"} %></th>
        </tr>
        <tr>
            <td>Monday</td>
            <td><%= form.number_field :val1, step: 0.25%></td>
            <td><%= form.number_field :val1, step: 0.25%></td>
        </tr>
        <tr>
            <td></td>
            <td><%= form.text_area :val1 %></td>
            <td><%= form.text_area :val1 %></td>
        </tr>
        <tr>
            <td>Tuesday</td>
        </tr>
        <tr>
            <td>Wednesday</td>
        </tr>
        <tr>
            <td>Thursday</td>
        </tr>
        <tr>
            <td>Friday</td>
        </tr>
        <tr>
            <td>Saturday</td>
        </tr>
        <tr>
            <td>Sunday</td>
        </tr>

    </table>
    <br>
    <p>Progress Comment</p>
    <%= form.text_field :progress_comment %>
    <br>
    <br>

    <%= form.submit "Create" %>
<% end %>