config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
  resources :projects
  resources :project_roles
  resources :users
  resources :time_logs
  resources :form_bulk_time_logs
end

app/models/user.rb
class User < ApplicationRecord
    has_many :project_roles
    has_many :projects, through: :project_roles

    has_many :time_logs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def new

    end
    def destroy 
        if User.find(params[:id]).destroy
            redirect_to users_path
        else
            redirect_to root_path
        end
    end
    def create
        @user = User.new(user_params)
        if( @user.save )
            redirect_to users_path
        else
            redirect_to root_path
        end
    end
    def user_params
        params.require(:user).permit(
            :last_name 
        )
    end
end

app/views/users/_index_nav.html.erb
<%=  link_to 'New', new_user_path %>

app/views/users/index.html.erb
<%= render 'pages/level1_nav' %>
<h1>Users</h1>
<%= render 'index_nav' %>
<table cellpadding="5">
    <tr>
        <th>delete?</th>
        <th>id</th>
        <th>last_name</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= button_to "Delete", User.find(user.id), :method => :delete %></td>
            <td><%= user.id %></td>
            <td><%= link_to user.last_name, user_path(user) %></td>
            <td><%= user.created_at %></td>
            <td><%= user.updated_at %></td>
        </tr>
    <%end %>
</table>

app/views/users/new.html.erb
<%= render 'pages/level1_nav' %>
<h1>New User</h1>

<%= form_with model: User do |form| %>
    <p>Last Name</p>
    <%= form.text_field :last_name %>
    <br>
    <br>

    <%= form.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<%= render 'pages/level1_nav' %>
<h1><%= @user.last_name %></h1>

<p><strong>Projects</strong></p>
<table cellpadding="5">
    <%@user.projects.sort_by {|obj| obj.name}.each do |project| %>
        <tr>
            <td>
                <%= link_to project.name, project_path(project) %>
            </td>
        </tr>
    <%end%>

</table>

<p><strong>Time Logs</strong></p>
<table cellpadding="5">
    <tr>
        <th>Project</th>
        <th>Progress comment</th>
    </tr>
    <%@user.time_logs.each do |time_log| %>
        <tr>
            <td>
                <%= time_log.project.name %>
            </td>
            <td>
                <%= time_log.progress_comment %>
            </td>
        </tr>
    <%end%>
</table>