config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
  resources :projects
  resources :project_roles
  resources :users
  resources :time_logs
  resources :form_bulk_time_logs
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :project_roles
    has_many :users, through: :project_roles

    has_many :time_logs
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = Project.all
    end
    def show 
        @project = Project.find(params[:id])
    end
    def destroy 
        if Project.find(params[:id]).destroy
            redirect_to projects_path
        else
            redirect_to root_path
        end
    end
    def create
        @project = Project.new(project_params)
        if( @project.save )
            redirect_to projects_path
        else
            redirect_to root_path
        end
    end

    def project_params
        params.require(:project).permit(
            :name 
        )
    end

end

app/views/projects/_index_nav.html.erb
<%=  link_to 'New', new_project_path %>

app/views/projects/index.html.erb
<%= render 'pages/level1_nav' %>
<h1>Projects</h1>
<%= render 'index_nav' %>
<table cellpadding="5">
    <tr>
        <th>delete?</th>
        <th>id</th>
        <th>name</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
    <% @projects.each do |project| %>
        <tr>
            <td><%= button_to "Delete", Project.find(project.id), :method => :delete %></td>
            <td><%= project.id %></td>
            <td><%= link_to project.name, project_path(project) %></td>
            <td><%= project.created_at %></td>
            <td><%= project.updated_at %></td>
        </tr>
    <%end %>
</table>

app/views/projects/new.html.erb
<%= render 'pages/level1_nav' %>
<h1>New Project</h1>

<%= form_with model: Project do |form| %>
    <p>Name</p>
    <%= form.text_field :name, value:"" %>
    <br>
    <br>

    <%= form.submit "Create" %>
<% end %>

app/views/projects/show.html.erb
<%= render 'pages/level1_nav' %>
<h1><%= @project.name %></h1>

<p><strong>Users</strong></p>
<table cellpadding="5">
    <%@project.users.sort_by {|obj| obj.last_name}.each do |user| %>
        <tr>
            <td>
                <%= link_to user.last_name, user_path(user) %>
            </td>
        </tr>
    <%end%>
</table>


<p><strong>Assign User to Project</strong></p>
<%= form_with model: ProjectRole do |form| %>
    <%= form.select :user_id, User.all.collect { |user| [user.last_name, user.id] }, {:prompt => "Select user"} %>
    <%= form.hidden_field :project_id, value: @project.id %>
    <%= form.submit "Assign" %>
<% end %>

<p><strong>Time Logs</strong></p>
<table cellpadding="5">
    <tr>
        <th>User</th>
        <th>Progress comment</th>
    </tr>
    <%@project.time_logs.each do |time_log| %>
        <tr>
            <td>
                <%= time_log.user.last_name %>
            </td>
            <td>
                <%= time_log.progress_comment %>
            </td>
        </tr>
    <%end%>
</table>